repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.12.10'
    hooks:
      - id: ruff
        args: ['--fix']

  - repo: https://github.com/hhatto/autopep8
    rev: 'v2.3.2'
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.17.1'
    hooks:
      - id: mypy
        args: ['--strict']
        additional_dependencies:
          - types-setuptools
          - typing_extensions
