name: verify

on:
  workflow_dispatch:
  push:

# job ideas taken from here: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4.3.1
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c #v4.9.1
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install ruff
      - name: Lint with Ruff
        run: ruff check --output-format=github .
        continue-on-error: false

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4.3.1
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c #v4.9.1
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install --require-hashes -r requirements.txt
      - name: Run tests
        run: python -m unittest

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4.3.1
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c #v4.9.1
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install build
      - name: Build package
        run: python -m build

  slackNotificaton:
    if: failure()
    needs: [lint, test, build]
    uses: ./.github/workflows/slack-notification.yaml
    with:
      channel: '#dada-prime'
      job_status: 'failure'
    secrets: inherit

